// Code generated by protoc-registry. DO NOT EDIT.
// Source: registry.yaml

package protocol

// TrustDomain names the class of key that signed an envelope. Every envelope
// declares exactly one.
type TrustDomain string

const (
	TrustDomainSaaSAttested TrustDomain = "saas-attested"
	TrustDomainTenant       TrustDomain = "tenant"
)

// Capability is a token a signer must hold, resolved through its delegation
// chain, before an event type may be accepted from it.
type Capability string

const (
	CapabilityAgentLifecycle     Capability = "agent.lifecycle"
	CapabilityAuditWrite         Capability = "audit.write"
	CapabilityCommandExecute     Capability = "command.execute"
	CapabilityCommandIssue       Capability = "command.issue"
	CapabilityInteractionRequest Capability = "interaction.request"
	CapabilityInteractionResolve Capability = "interaction.resolve"
	CapabilityQueryIssue         Capability = "query.issue"
	CapabilityQueryServe         Capability = "query.serve"
	CapabilityThreadWrite        Capability = "thread.write"
)

// Durability selects the transport guarantee for an event type.
type Durability string

const (
	// DurabilityJetStream events are published to a JetStream stream and are
	// redelivered until acknowledged.
	DurabilityJetStream Durability = "jetstream"
	// DurabilityCore events are published to core NATS with no stream behind
	// them; they are request-scoped and are not replayed.
	DurabilityCore Durability = "core"
)

var eventTrustDomains = map[EventType][]TrustDomain{
	EventAgentLifecycle:      {TrustDomainTenant},
	EventAgentUsage:          {TrustDomainTenant},
	EventAuditIncident:       {TrustDomainTenant},
	EventAuditSchema:         {TrustDomainTenant},
	EventAuditSecurity:       {TrustDomainTenant},
	EventAuditSignature:      {TrustDomainTenant},
	EventChatMessage:         {TrustDomainTenant, TrustDomainSaaSAttested},
	EventCommandRequested:    {TrustDomainTenant, TrustDomainSaaSAttested},
	EventCommandResult:       {TrustDomainTenant},
	EventDecisionRecord:      {TrustDomainTenant},
	EventPermissionRequested: {TrustDomainTenant},
	EventPermissionResolved:  {TrustDomainTenant, TrustDomainSaaSAttested},
	EventQueryRequest:        {TrustDomainTenant, TrustDomainSaaSAttested},
	EventQueryResult:         {TrustDomainTenant},
	EventQuestionRequested:   {TrustDomainTenant},
	EventQuestionResolved:    {TrustDomainTenant, TrustDomainSaaSAttested},
	EventToolCall:            {TrustDomainTenant},
	EventToolResult:          {TrustDomainTenant},
}

var eventCapabilities = map[EventType][]Capability{
	EventAgentLifecycle:      {CapabilityAgentLifecycle},
	EventAgentUsage:          {CapabilityThreadWrite},
	EventAuditIncident:       {CapabilityAuditWrite},
	EventAuditSchema:         {CapabilityAuditWrite},
	EventAuditSecurity:       {CapabilityAuditWrite},
	EventAuditSignature:      {CapabilityAuditWrite},
	EventChatMessage:         {CapabilityThreadWrite},
	EventCommandRequested:    {CapabilityCommandIssue},
	EventCommandResult:       {CapabilityCommandExecute},
	EventDecisionRecord:      {CapabilityThreadWrite},
	EventPermissionRequested: {CapabilityInteractionRequest},
	EventPermissionResolved:  {CapabilityInteractionResolve},
	EventQueryRequest:        {CapabilityQueryIssue},
	EventQueryResult:         {CapabilityQueryServe},
	EventQuestionRequested:   {CapabilityInteractionRequest},
	EventQuestionResolved:    {CapabilityInteractionResolve},
	EventToolCall:            {CapabilityThreadWrite},
	EventToolResult:          {CapabilityThreadWrite},
}

var eventDurability = map[EventType]Durability{
	EventAgentLifecycle:      DurabilityJetStream,
	EventAgentUsage:          DurabilityJetStream,
	EventAuditIncident:       DurabilityJetStream,
	EventAuditSchema:         DurabilityJetStream,
	EventAuditSecurity:       DurabilityJetStream,
	EventAuditSignature:      DurabilityJetStream,
	EventChatMessage:         DurabilityJetStream,
	EventCommandRequested:    DurabilityJetStream,
	EventCommandResult:       DurabilityJetStream,
	EventDecisionRecord:      DurabilityJetStream,
	EventPermissionRequested: DurabilityJetStream,
	EventPermissionResolved:  DurabilityJetStream,
	EventQueryRequest:        DurabilityCore,
	EventQueryResult:         DurabilityCore,
	EventQuestionRequested:   DurabilityJetStream,
	EventQuestionResolved:    DurabilityJetStream,
	EventToolCall:            DurabilityJetStream,
	EventToolResult:          DurabilityJetStream,
}
