// Code generated by protoc-registry. DO NOT EDIT.
// Source: registry.yaml

package protocol

// EventType is a registry type token. It is simultaneously the envelope
// event_type, the trailing token of the subject, and the payload schema
// basename, so the three can never drift.
type EventType string

// The protocol version this binding implements, from the registry. The subject
// root carries MAJOR only: an unknown MAJOR is rejected, an unknown MINOR is
// accepted.
const (
	ProtocolVersion = "1.3"
	ProtocolMajor   = 1
	ProtocolMinor   = 3
)

const (
	EventAgentLifecycle      EventType = "agent.lifecycle"
	EventAuditIncident       EventType = "audit.incident"
	EventAuditSchema         EventType = "audit.schema"
	EventAuditSecurity       EventType = "audit.security"
	EventAuditSignature      EventType = "audit.signature"
	EventChatMessage         EventType = "chat.message"
	EventCommandRequested    EventType = "command.requested"
	EventCommandResult       EventType = "command.result"
	EventDecisionRecord      EventType = "decision.record"
	EventPermissionRequested EventType = "permission.requested"
	EventPermissionResolved  EventType = "permission.resolved"
	EventQuestionRequested   EventType = "question.requested"
	EventQuestionResolved    EventType = "question.resolved"
	EventToolCall            EventType = "tool.call"
	EventToolResult          EventType = "tool.result"
)

// eventTypes is sorted by token so that AllEventTypes is deterministic.
var eventTypes = []EventType{
	EventAgentLifecycle,
	EventAuditIncident,
	EventAuditSchema,
	EventAuditSecurity,
	EventAuditSignature,
	EventChatMessage,
	EventCommandRequested,
	EventCommandResult,
	EventDecisionRecord,
	EventPermissionRequested,
	EventPermissionResolved,
	EventQuestionRequested,
	EventQuestionResolved,
	EventToolCall,
	EventToolResult,
}

// eventTypeSet backs ParseEventType.
var eventTypeSet = map[EventType]struct{}{
	EventAgentLifecycle:      {},
	EventAuditIncident:       {},
	EventAuditSchema:         {},
	EventAuditSecurity:       {},
	EventAuditSignature:      {},
	EventChatMessage:         {},
	EventCommandRequested:    {},
	EventCommandResult:       {},
	EventDecisionRecord:      {},
	EventPermissionRequested: {},
	EventPermissionResolved:  {},
	EventQuestionRequested:   {},
	EventQuestionResolved:    {},
	EventToolCall:            {},
	EventToolResult:          {},
}

// schemaPaths maps each event type to its payload schema, relative to the
// repository root and to the embedded schema filesystem alike.
var schemaPaths = map[EventType]string{
	EventAgentLifecycle:      "schemas/payload/agent.lifecycle.json",
	EventAuditIncident:       "schemas/payload/audit.incident.json",
	EventAuditSchema:         "schemas/payload/audit.schema.json",
	EventAuditSecurity:       "schemas/payload/audit.security.json",
	EventAuditSignature:      "schemas/payload/audit.signature.json",
	EventChatMessage:         "schemas/payload/chat.message.json",
	EventCommandRequested:    "schemas/payload/command.requested.json",
	EventCommandResult:       "schemas/payload/command.result.json",
	EventDecisionRecord:      "schemas/payload/decision.record.json",
	EventPermissionRequested: "schemas/payload/permission.requested.json",
	EventPermissionResolved:  "schemas/payload/permission.resolved.json",
	EventQuestionRequested:   "schemas/payload/question.requested.json",
	EventQuestionResolved:    "schemas/payload/question.resolved.json",
	EventToolCall:            "schemas/payload/tool.call.json",
	EventToolResult:          "schemas/payload/tool.result.json",
}
