// Code generated by protoc-registry. DO NOT EDIT.
// Source: registry.yaml

package protocol

import "time"

// Retention is a JetStream retention policy.
type Retention string

const (
	RetentionLimits    Retention = "limits"
	RetentionWorkQueue Retention = "workqueue"
)

// Discard is a JetStream discard policy: which message is dropped when a limit
// is reached.
type Discard string

const (
	DiscardOld Discard = "old"
)

// streamTemplate is a stream specification with the tenant and workspace tokens
// still unresolved. StreamsFor substitutes them.
type streamTemplate struct {
	name            string
	subjects        []string
	retention       Retention
	maxAge          time.Duration
	discard         Discard
	duplicateWindow time.Duration
}

var streamTemplates = []streamTemplate{
	{
		name: "OL_EVENTS_{workspace_id}",
		subjects: []string{
			"ol.v1.tenant.{tenant_id}.workspace.{workspace_id}.audit.>",
			"ol.v1.tenant.{tenant_id}.workspace.{workspace_id}.conductor.*.result.*.>",
			"ol.v1.tenant.{tenant_id}.workspace.{workspace_id}.thread.*.event.>",
		},
		retention:       RetentionLimits,
		maxAge:          2160 * time.Hour,
		discard:         DiscardOld,
		duplicateWindow: 2 * time.Hour,
	},
	{
		name: "OL_COMMANDS_{workspace_id}",
		subjects: []string{
			"ol.v1.tenant.{tenant_id}.workspace.{workspace_id}.conductor.*.command.>",
		},
		retention:       RetentionWorkQueue,
		maxAge:          24 * time.Hour,
		discard:         DiscardOld,
		duplicateWindow: 2 * time.Hour,
	},
}
