// Code generated by protoc-registry. DO NOT EDIT.
// Source: registry.yaml

package protocol

// subjectClass selects a subject template.
type subjectClass string

const (
	subjectClassAudit                subjectClass = "audit"
	subjectClassConductorCommand     subjectClass = "conductor_command"
	subjectClassConductorQuery       subjectClass = "conductor_query"
	subjectClassConductorQueryResult subjectClass = "conductor_query_result"
	subjectClassConductorResult      subjectClass = "conductor_result"
	subjectClassThread               subjectClass = "thread"
)

// subjectTemplates is the subject grammar. {type} is always the final token
// and is the only token that may contain a dot.
var subjectTemplates = map[subjectClass]string{
	subjectClassAudit:                "ol.v1.tenant.{tenant_id}.workspace.{workspace_id}.audit.{type}",
	subjectClassConductorCommand:     "ol.v1.tenant.{tenant_id}.workspace.{workspace_id}.conductor.{conductor_id}.command.{type}",
	subjectClassConductorQuery:       "ol.v1.tenant.{tenant_id}.workspace.{workspace_id}.conductor.{conductor_id}.query.{type}",
	subjectClassConductorQueryResult: "ol.v1.tenant.{tenant_id}.workspace.{workspace_id}.conductor.{conductor_id}.query_result.{query_id}.{type}",
	subjectClassConductorResult:      "ol.v1.tenant.{tenant_id}.workspace.{workspace_id}.conductor.{conductor_id}.result.{command_id}.{type}",
	subjectClassThread:               "ol.v1.tenant.{tenant_id}.workspace.{workspace_id}.thread.{thread_id}.event.{type}",
}

var eventSubjectClasses = map[EventType]subjectClass{
	EventAgentLifecycle:      subjectClassThread,
	EventAuditIncident:       subjectClassAudit,
	EventAuditSchema:         subjectClassAudit,
	EventAuditSecurity:       subjectClassAudit,
	EventAuditSignature:      subjectClassAudit,
	EventChatMessage:         subjectClassThread,
	EventCommandRequested:    subjectClassConductorCommand,
	EventCommandResult:       subjectClassConductorResult,
	EventDecisionRecord:      subjectClassThread,
	EventPermissionRequested: subjectClassThread,
	EventPermissionResolved:  subjectClassThread,
	EventQueryRequest:        subjectClassConductorQuery,
	EventQueryResult:         subjectClassConductorQueryResult,
	EventQuestionRequested:   subjectClassThread,
	EventQuestionResolved:    subjectClassThread,
	EventToolCall:            subjectClassThread,
	EventToolResult:          subjectClassThread,
}
