package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
)

// header is on every generated Go file. golangci-lint recognises this exact
// form and suppresses findings in generated code; `git diff --exit-code` after
// `make generate` is what actually keeps these files honest.
const header = `// Code generated by protoc-registry. DO NOT EDIT.
// Source: registry.yaml

package protocol
`

// goPackageDir is where the generated Go binding lives, relative to the root.
var goPackageDir = filepath.Join("go", "protocol")

// writeGo formats body, prepends the generated header, and writes it only when
// the content differs, so an unchanged registry leaves mtimes alone.
func writeGo(root, name string, body *bytes.Buffer) error {
	var out bytes.Buffer
	out.WriteString(header)
	out.WriteString(body.String())

	formatted, err := format.Source(out.Bytes())
	if err != nil {
		return fmt.Errorf("formatting %s: %w\n%s", name, err, out.String())
	}
	return writeFile(filepath.Join(root, goPackageDir, name), formatted)
}

func writeFile(path string, content []byte) error {
	//nolint:gosec // path is composed from the -root flag and generator constants
	if existing, err := os.ReadFile(path); err == nil && bytes.Equal(existing, content) {
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		return fmt.Errorf("creating %s: %w", filepath.Dir(path), err)
	}
	if err := os.WriteFile(path, content, 0o644); err != nil { //nolint:gosec // generated source is world-readable by design
		return fmt.Errorf("writing %s: %w", path, err)
	}
	return nil
}

// acronyms fixes the casing that a naive title-caser gets wrong. It is keyed by
// the lowercase token so that "saas-attested" becomes SaaSAttested rather than
// SaasAttested.
var acronyms = map[string]string{
	"saas":      "SaaS",
	"id":        "ID",
	"url":       "URL",
	"ttl":       "TTL",
	"workqueue": "WorkQueue",
	"jetstream": "JetStream",
}

// goName converts a registry token such as "permission.requested" or
// "saas-attested" into an exported Go identifier.
func goName(token string) string {
	var b strings.Builder
	for _, part := range strings.FieldsFunc(token, func(r rune) bool { return r == '.' || r == '-' || r == '_' }) {
		if fixed, ok := acronyms[part]; ok {
			b.WriteString(fixed)
			continue
		}
		b.WriteString(strings.ToUpper(part[:1]))
		b.WriteString(part[1:])
	}
	return b.String()
}

// unexportedGoName is goName with a lowercase first rune, for package-private
// generated identifiers.
func unexportedGoName(token string) string {
	name := goName(token)
	return strings.ToLower(name[:1]) + name[1:]
}

// quote renders a Go string literal. Registry tokens never contain a quote or a
// backslash - the registry schema restricts them - so %q is exact here.
func quote(s string) string { return fmt.Sprintf("%q", s) }
