package main

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"
)

// TestGeneratedFilesAreCurrent regenerates into a scratch tree and compares the
// result to what is committed. It is the drift gate expressed as a test, so a
// hand-edit of a generated file fails `make test`, not only `make check`.
func TestGeneratedFilesAreCurrent(t *testing.T) {
	root := repoRoot(t)
	reg, err := loadRegistry(root)
	require.NoError(t, err)

	scratch := t.TempDir()
	for _, step := range generators() {
		require.NoError(t, step.fn(scratch, reg), step.name)
	}

	committed := filepath.Join(root, goPackageDir)
	generated := filepath.Join(scratch, goPackageDir)

	entries, err := os.ReadDir(generated)
	require.NoError(t, err)
	require.NotEmpty(t, entries)

	for _, entry := range entries {
		want, err := os.ReadFile(filepath.Join(generated, entry.Name()))
		require.NoError(t, err)
		got, err := os.ReadFile(filepath.Join(committed, entry.Name()))
		require.NoError(t, err, "%s is missing; run make generate", entry.Name())
		require.Equal(t, string(want), string(got), "%s is stale; run make generate", entry.Name())
	}
}

// TestGenerationIsDeterministic proves that regeneration is byte-stable, which
// is what makes `git diff --exit-code` a meaningful gate rather than noise.
func TestGenerationIsDeterministic(t *testing.T) {
	root := repoRoot(t)
	reg, err := loadRegistry(root)
	require.NoError(t, err)

	first, second := t.TempDir(), t.TempDir()
	for _, dir := range []string{first, second} {
		for _, step := range generators() {
			require.NoError(t, step.fn(dir, reg), step.name)
		}
	}

	entries, err := os.ReadDir(filepath.Join(first, goPackageDir))
	require.NoError(t, err)
	for _, entry := range entries {
		a, err := os.ReadFile(filepath.Join(first, goPackageDir, entry.Name()))
		require.NoError(t, err)
		b, err := os.ReadFile(filepath.Join(second, goPackageDir, entry.Name()))
		require.NoError(t, err)
		require.Equal(t, string(a), string(b), entry.Name())
	}
}

// TestGeneratedFilesCarryTheHeader is what tells golangci-lint, code review,
// and `go generate` consumers that these files are not hand-editable.
func TestGeneratedFilesCarryTheHeader(t *testing.T) {
	root := repoRoot(t)
	matches, err := filepath.Glob(filepath.Join(root, goPackageDir, "*_gen.go"))
	require.NoError(t, err)
	require.NotEmpty(t, matches)

	for _, path := range matches {
		content, err := os.ReadFile(path)
		require.NoError(t, err)
		require.Contains(t, string(content), "// Code generated by protoc-registry. DO NOT EDIT.", path)
	}
}
