package main

import (
	"io/fs"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"
)

// TestGeneratedFilesAreCurrent regenerates into a scratch tree and compares the
// result to what is committed. It is the drift gate expressed as a test, so a
// hand-edit of a generated file fails `make test`, not only `make check`.
func TestGeneratedFilesAreCurrent(t *testing.T) {
	root := repoRoot(t)
	reg, err := loadRegistry(root)
	require.NoError(t, err)

	scratch := scratchRoot(t, root)
	for _, step := range generators() {
		require.NoError(t, step.fn(scratch, reg), step.name)
	}

	for _, dir := range generatedDirs() {
		committed := filepath.Join(root, dir)
		generated := filepath.Join(scratch, dir)

		files := generatedFiles(t, generated)
		require.NotEmpty(t, files, dir)

		for _, rel := range files {
			want, err := os.ReadFile(filepath.Join(generated, rel))
			require.NoError(t, err)
			got, err := os.ReadFile(filepath.Join(committed, rel))
			require.NoError(t, err, "%s is missing; run make generate", rel)
			require.Equal(t, string(want), string(got), "%s/%s is stale; run make generate", dir, rel)
		}
	}
}

// generatedDirs are the trees whose entire contents the generator owns.
func generatedDirs() []string {
	return []string{goPackageDir, filepath.FromSlash(signingDir)}
}

// scratchRoot is an empty repository root that carries only the generator's
// hand-written inputs, so that generation into it starts from nothing.
func scratchRoot(t *testing.T, root string) string {
	t.Helper()
	dir := t.TempDir()
	for _, input := range []string{schemaDir, validFixtureDir, badFixtureDir} {
		require.NoError(t, filepath.WalkDir(filepath.Join(root, filepath.FromSlash(input)), func(p string, d fs.DirEntry, err error) error {
			if err != nil || d.IsDir() {
				return err
			}
			rel, err := filepath.Rel(root, p)
			if err != nil {
				return err
			}
			body, err := os.ReadFile(p)
			if err != nil {
				return err
			}
			dst := filepath.Join(dir, rel)
			if err := os.MkdirAll(filepath.Dir(dst), 0o750); err != nil {
				return err
			}
			return os.WriteFile(dst, body, 0o600)
		}))
	}
	return dir
}

// generatedFiles lists every file under dir, relative to it.
func generatedFiles(t *testing.T, dir string) []string {
	t.Helper()
	var out []string
	require.NoError(t, filepath.WalkDir(dir, func(p string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return err
		}
		rel, err := filepath.Rel(dir, p)
		if err != nil {
			return err
		}
		out = append(out, rel)
		return nil
	}))
	return out
}

// TestGenerationIsDeterministic proves that regeneration is byte-stable, which
// is what makes `git diff --exit-code` a meaningful gate rather than noise.
func TestGenerationIsDeterministic(t *testing.T) {
	root := repoRoot(t)
	reg, err := loadRegistry(root)
	require.NoError(t, err)

	first, second := scratchRoot(t, root), scratchRoot(t, root)
	for _, dir := range []string{first, second} {
		for _, step := range generators() {
			require.NoError(t, step.fn(dir, reg), step.name)
		}
	}

	for _, dir := range generatedDirs() {
		for _, rel := range generatedFiles(t, filepath.Join(first, dir)) {
			a, err := os.ReadFile(filepath.Join(first, dir, rel))
			require.NoError(t, err)
			b, err := os.ReadFile(filepath.Join(second, dir, rel))
			require.NoError(t, err)
			require.Equal(t, string(a), string(b), rel)
		}
	}
}

// TestGeneratedFilesCarryTheHeader is what tells golangci-lint, code review,
// and `go generate` consumers that these files are not hand-editable.
func TestGeneratedFilesCarryTheHeader(t *testing.T) {
	root := repoRoot(t)
	matches, err := filepath.Glob(filepath.Join(root, goPackageDir, "*_gen.go"))
	require.NoError(t, err)
	require.NotEmpty(t, matches)

	for _, path := range matches {
		content, err := os.ReadFile(path)
		require.NoError(t, err)
		require.Contains(t, string(content), "// Code generated by protoc-registry. DO NOT EDIT.", path)
	}
}
